codereader/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'codereader.views',
    url(r'^projects/$', "project_list", name="project_list"),
    url(r'^project/new/', "project_add", name="project_add"),
    url(r'^project/([\w-]+)/$', "project_details", name="project_details"),

    url(r'^project/([\w-]+)/repository/([\d]+)/', "repository_show", name="repository_show"),
    url(r'^project/([\w-]+)/repository/new/$', "repository_add",
        name="repository_add"),
)

main/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'main.views',
    url(r'^$', 'home', name='home'),
)

readthecode/urls.py
"""Root URLconf"""
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name="home.html")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('codereader.urls')),
)


if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)$', 'serve',
         {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

codereader/models.py
import os
from django.db import models
from django.conf import settings
from django.utils.text import slugify


class Project(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    homepage_url = models.URLField(max_length=255, blank=True)

    def __unicode__(self):
        return "{}".format(self.name)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Project, self).save(*args, **kwargs)


class Repository(models.Model):
    project = models.ForeignKey(Project)
    origin_url = models.CharField(max_length=255, blank=True)

    def __unicode__(self):
        return "{}: {}".format(self.project.name, self.origin_url)

    @property
    def code_root(self):
        return os.path.join(settings.MEDIA_ROOT, "repositories",
                            self.project.slug)

    def files(self):
        repo_structure = {}
        for (dirpath, dirnames, filenames) in os.walk(self.code_root):
            rel_path = dirpath[len(self.code_root):]
            repo_structure_dir = repo_structure
            dirs = rel_path.split('/')
            for dirname in dirs:
                if dirname:
                    repo_structure_dir = repo_structure_dir[dirname]
            for filename in filenames:
                repo_structure_dir[filename] = filename
            for dirname in dirnames:
                repo_structure_dir[dirname] = {}
        return repo_structure

main/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


#class Document(models.Model):
#    title = models.CharField(max_length=255)
#    slug = models.SlugField()
#    author = models.ForeignKey(User)
#    content = models.TextField()
#    created_at = models.DateTimeField(auto_now=True)
#
#    class Meta:
#        ordering = ['-created_at']
#
#    def __unicode__(self):
#        return self.title
#
#    def get_absolute_url(self):
#        return '/my-object/%s-%d' % (self.slug, self.id)
#
#    def save(self, *args, **kwargs):
#        self.slug = slugify("%s-%d" % (self.title, self.id))

codereader/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from . import models
from . import tasks


class CrispyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CrispyForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.add_input(Submit('save', "Save"))


class ProjectForm(CrispyForm):
    class Meta:
        model = models.Project
        fields = ('name', 'homepage_url', 'description')


class RepositoryForm(CrispyForm):
    class Meta:
        model = models.Repository
        fields = ('origin_url', )

    def __init__(self, *args, **kwargs):
        self.project = kwargs.pop('project')
        super(RepositoryForm, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        print self.project
        self.instance.project = self.project
        self.cleaned_data['project'] = self.project
        repo = super(RepositoryForm, self).save(*args, **kwargs)
        tasks.import_repo.delay(repo.origin_url, repo.project.slug)
        return repo

codereader/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse

from . import forms
from . import models


def project_list(request):
    projects = models.Project.objects.all()
    context = {'projects': projects}
    return render(request, "codereader/project_list.html", context)


def project_details(request, slug):
    project = models.Project.objects.get(slug=slug)
    context = {'project': project}
    return render(request, "codereader/project_details.html", context)


def project_add(request):
    form = forms.ProjectForm(request.POST or None)
    if form.is_valid():
        project = form.save()
        return redirect(reverse("project_details", args=(project.slug, )))
    context = {'form': form}
    return render(request, "codereader/project_form.html", context)


def repository_show(request, slug, repo_id):
    repository = models.Repository.objects.get(pk=repo_id)
    context = {'repository': repository}
    return render(request, "codereader/repository_details.html", context)


def repository_add(request, slug):
    project = models.Project.objects.get(slug=slug)
    form = forms.RepositoryForm(request.POST or None, project=project)
    if form.is_valid():
        form.save()
        return redirect(reverse("project_details", args=(slug, )))
    context = {'form': form}
    return render(request, "codereader/repository_form.html", context)

main/views.py
# -*- coding: utf-8 -*-
"""Main app views"""

# pylint: disable=E1101

from django.shortcuts import render


def home(request):
    """Homepage view"""
    return render(request, 'home.html')

templates/base.html
{% load compress %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <link type="text/plain" rel="author" href="/humans.txt">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/normalize.css">
    <script src="{{ STATIC_URL }}jquery/jquery.js"></script>
    {% compress css %}
    <link type="text/less" rel="stylesheet" href="{{ STATIC_URL }}bootstrap/less/bootstrap.less" charset="utf-8">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <!-- <link type="text/less" rel="stylesheet" href="{{ STATIC_URL }}bootstrap/less/responsive.less" charset="utf-8"> -->
    {% endcompress %}
    {% compress css %}
    <link type="text/less" rel="stylesheet" href="{{ STATIC_URL }}css/main.less" charset="utf-8">
    {% endcompress %}
    <script src="{{ STATIC_URL }}js/modernizr-2.6.1.min.js"></script>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="{{ STATIC_URL }}images/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{ STATIC_URL }}images/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{ STATIC_URL }}images/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{ STATIC_URL }}images/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="{{ STATIC_URL }}images/apple-touch-icon-57-precomposed.png">
  </head>
  <body>
    <!--[if lt IE 7]>
        <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
    <![endif]-->

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <a class="brand" href="#">Project name</a>

      <div class="nav-collapse collapse">
        <p class="navbar-text pull-right">
          Logged in as <a href="#" class="navbar-link">Username</a>
        </p>
        <ul class="nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div><!--/.nav-collapse -->

    </div>
  </div>
</div>

	<div id="wrapper">
		<header id="header" role="banner">
			<div class="content">
				<h1 class="site-name"><a href="/"></a></h1>
				<nav role="navigation">
					<ul>

					</ul>
				</nav>
			</div>
		</header>
    <div class='container-fluid'>
      {% block content %}{% endblock %}
      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div><!--/.fluid-container-->

  </div>
{% compress js %}

<script src="{{ STATIC_URL }}bootstrap/js/bootstrap-transition.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap-alert.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap-modal.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap-dropdown.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap-scrollspy.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap-tab.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap-tooltip.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap-popover.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap-button.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap-collapse.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap-carousel.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap-typeahead.js"></script>

{% endcompress %}
<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));
</script>
</body>
</html>

templates/codereader/project_details.html
{% extends "base.html" %}

{% block content %}
<h1>{{ project.name }}</h1>
<p>{{ project.description }}</p>
{% for repository in project.repository_set.all %}
  <a href='{% url "repository_show" project.slug repository.id %}'>{{ repository.origin_url }}</a><br/>
{% endfor %}
<a href="{% url "repository_add" project.slug %}">Add repository</a>
{% endblock %}

templates/codereader/project_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

templates/codereader/project_list.html
{% extends "base.html" %}

{% block content %}
{% for project in projects %}
  <a href="{% url "project_details" project.slug %}">{{ project.name }}</a> 
{% endfor %}
{% endblock %}

templates/codereader/repository_details.html
{% extends "base.html" %}
{% load sourcebrowser %}

{% block content %}
<div class="row">
  <div class="span3">
    {% source_tree repository.files %}
  </div>
</div>
  
{% endblock %}

templates/codereader/repository_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}
  
{% endblock %}